# Generated by Django 3.1.4 on 2020-12-26 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cars_brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='conditionals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='drivers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('familia', models.CharField(max_length=200)),
                ('otchestvo', models.CharField(max_length=200)),
                ('license_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='reasons_DTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=228)),
            ],
        ),
        migrations.CreateModel(
            name='type_incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=8)),
                ('insurance_number', models.CharField(max_length=100)),
                ('cars_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GAI.cars_brand')),
            ],
        ),
        migrations.CreateModel(
            name='cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('place', models.CharField(max_length=500)),
                ('died_count', models.IntegerField()),
                ('injured_count', models.IntegerField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GAI.cars')),
                ('conditional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GAI.conditionals')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GAI.drivers')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GAI.type_incident')),
                ('reasons', models.ManyToManyField(to='GAI.reasons_DTP')),
            ],
        ),
    ]
